<?php

namespace Database\Seeders;

use App\Models\State;
use App\Models\Dist;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $states = [
            [
                'stateCode' => 'AP',
                'state' => 'Andhra Pradesh',
                'districts' => [
                    ['districtCode' => 'SRI', 'district' => 'Srikakulam'],
                    ['districtCode' => 'PAR', 'district' => 'Parvathipuram Manyam'],
                    ['districtCode' => 'VIZ', 'district' => 'Vizianagaram'],
                    ['districtCode' => 'VIS', 'district' => 'Visakhapatnam'],
                    ['districtCode' => 'ALL', 'district' => 'Alluri Sitharama Raju'],
                    ['districtCode' => 'ANA', 'district' => 'Anakapalli'],
                    ['districtCode' => 'KAK', 'district' => 'Kakinada'],
                    ['districtCode' => 'EAS', 'district' => 'East Godavari'],
                    ['districtCode' => 'KON', 'district' => 'Konaseema'],
                    ['districtCode' => 'ELU', 'district' => 'Eluru'],
                    ['districtCode' => 'WES', 'district' => 'West Godavari'],
                    ['districtCode' => 'NTR', 'district' => 'NTR'],
                    ['districtCode' => 'KRI', 'district' => 'Krishna'],
                    ['districtCode' => 'PAL', 'district' => 'Palnadu'],
                    ['districtCode' => 'GUN', 'district' => 'Guntur'],
                    ['districtCode' => 'BAP', 'district' => 'Bapatla'],
                    ['districtCode' => 'NEL', 'district' => 'Sri Potti'],
                    ['districtCode' => 'PRA', 'district' => 'Prakasam'],
                    ['districtCode' => 'KUR', 'district' => 'Kurnool'],
                    ['districtCode' => 'NAN', 'district' => 'Nandyal'],
                    ['districtCode' => 'ANA', 'district' => 'Anantapuramu'],
                    ['districtCode' => 'SSS', 'district' => 'Sri Sathya Sai'],
                    ['districtCode' => 'CUD', 'district' => 'YSR'],
                    ['districtCode' => 'ANN', 'district' => 'Annamayya'],
                    ['districtCode' => 'TIR', 'district' => 'Tirupati'],
                    ['districtCode' => 'CHI', 'district' => 'Chittoor'],
                ]
            ],
            [
                'stateCode' => 'AR',
                'state' => 'Arunachal Pradesh',
                'districts' => [
                    ['districtCode' => 'ANJ', 'district' => 'Anjaw'],
                    ['districtCode' => 'CHA', 'district' => 'Changlang'],
                    ['districtCode' => 'DIB', 'district' => 'Dibang Valley'],
                    ['districtCode' => 'EKA', 'district' => 'East Kameng'],
                    ['districtCode' => 'ESI', 'district' => 'East Siang'],
                    ['districtCode' => 'KAM', 'district' => 'Kamle'],
                    ['districtCode' => 'KDA', 'district' => 'Kra Daadi'],
                    ['districtCode' => 'KUR', 'district' => 'Kurung Kumey'],
                    ['districtCode' => 'LEP', 'district' => 'Lepa Rada'],
                    ['districtCode' => 'LOH', 'district' => 'Lohit'],
                    ['districtCode' => 'LON', 'district' => 'Longding'],
                    ['districtCode' => 'LOW', 'district' => 'Lower Dibang Valley'],
                    ['districtCode' => 'LSI', 'district' => 'Lower Siang'],
                    ['districtCode' => 'LSU', 'district' => 'Lower Subansiri'],
                    ['districtCode' => 'NAM', 'district' => 'Namsai'],
                    ['districtCode' => 'PAK', 'district' => 'Pakke-Kessang'],
                    ['districtCode' => 'PAP', 'district' => 'Papum Pare'],
                    ['districtCode' => 'SHI', 'district' => 'Shi Yomi'],
                    ['districtCode' => 'SIA', 'district' => 'Siang'],
                    ['districtCode' => 'TAW', 'district' => 'Tawang'],
                    ['districtCode' => 'TIR', 'district' => 'Tirap'],
                    ['districtCode' => 'UPP', 'district' => 'Upper Siang'],
                    ['districtCode' => 'UPS', 'district' => 'Upper Subansiri'],
                    ['districtCode' => 'WES', 'district' => 'West Kameng'],
                    ['districtCode' => 'WSI', 'district' => 'West Siang'],
                ]
            ],
            [
                'stateCode' => 'AS',
                'state' => 'Assam',
                'districts' => [
                    ['districtCode' => 'BAK', 'district' => 'Baksa'],
                    ['districtCode' => 'BAR', 'district' => 'Barpeta'],
                    ['districtCode' => 'BIS', 'district' => 'Biswanath'],
                    ['districtCode' => 'BON', 'district' => 'Bongaigaon'],
                    ['districtCode' => 'CAC', 'district' => 'Cachar'],
                    ['districtCode' => 'CHA', 'district' => 'Charaideo'],
                    ['districtCode' => 'CHI', 'district' => 'Chirang'],
                    ['districtCode' => 'DAR', 'district' => 'Darrang'],
                    ['districtCode' => 'DHE', 'district' => 'Dhemaji'],
                    ['districtCode' => 'DHU', 'district' => 'Dhubri'],
                    ['districtCode' => 'DIB', 'district' => 'Dibrugarh'],
                    ['districtCode' => 'DIM', 'district' => 'Dima Hasao'],
                    ['districtCode' => 'GOA', 'district' => 'Goalpara'],
                    ['districtCode' => 'GOL', 'district' => 'Golaghat'],
                    ['districtCode' => 'HAI', 'district' => 'Hailakandi'],
                    ['districtCode' => 'HOJ', 'district' => 'Hojai'],
                    ['districtCode' => 'JOR', 'district' => 'Jorhat'],
                    ['districtCode' => 'KAM', 'district' => 'Kamrup'],
                    ['districtCode' => 'KAM-M', 'district' => 'Kamrup Metropolitan'],
                    ['districtCode' => 'KAR', 'district' => 'Karbi Anglong'],
                    ['districtCode' => 'KAR-I', 'district' => 'Karimganj'],
                    ['districtCode' => 'KOK', 'district' => 'Kokrajhar'],
                    ['districtCode' => 'LAK', 'district' => 'Lakhimpur'],
                    ['districtCode' => 'MAJ', 'district' => 'Majuli'],
                    ['districtCode' => 'MOR', 'district' => 'Morigaon'],
                    ['districtCode' => 'NAG', 'district' => 'Nagaon'],
                    ['districtCode' => 'NAL', 'district' => 'Nalbari'],
                    ['districtCode' => 'SIV', 'district' => 'Sivasagar'],
                    ['districtCode' => 'SON', 'district' => 'Sonitpur'],
                    ['districtCode' => 'SOU', 'district' => 'South Salmara-Mankachar'],
                    ['districtCode' => 'TIN', 'district' => 'Tinsukia'],
                    ['districtCode' => 'UDA', 'district' => 'Udalguri'],
                    ['districtCode' => 'WES', 'district' => 'West Karbi Anglong'],
                    ['districtCode' => 'BIS-C', 'district' => 'Biswanath Chariali'],
                    ['districtCode' => 'BAJ', 'district' => 'Bajali'],
                ]
            ],
            [
                'stateCode' => 'BR',
                'state' => 'Bihar',
                'districts' => [
                    ['districtCode' => 'ARA', 'district' => 'Araria'],
                    ['districtCode' => 'AR', 'district' => 'Arwal'],
                    ['districtCode' => 'AU', 'district' => 'Aurangabad'],
                    ['districtCode' => 'BAN', 'district' => 'Banka'],
                    ['districtCode' => 'BEG', 'district' => 'Begusarai'],
                    ['districtCode' => 'BHA', 'district' => 'Bhagalpur'],
                    ['districtCode' => 'BHO', 'district' => 'Bhojpur'],
                    ['districtCode' => 'BUX', 'district' => 'Buxar'],
                    ['districtCode' => 'DAR', 'district' => 'Darbhanga'],
                    ['districtCode' => 'EAS', 'district' => 'East Champaran (Motihari)'],
                    ['districtCode' => 'GAY', 'district' => 'Gaya'],
                    ['districtCode' => 'GOP', 'district' => 'Gopalganj'],
                    ['districtCode' => 'JAM', 'district' => 'Jamui'],
                    ['districtCode' => 'JEH', 'district' => 'Jehanabad'],
                    ['districtCode' => 'KAI', 'district' => 'Kaimur (Bhabua)'],
                    ['districtCode' => 'KAT', 'district' => 'Katihar'],
                    ['districtCode' => 'KHA', 'district' => 'Khagaria'],
                    ['districtCode' => 'KIS', 'district' => 'Kishanganj'],
                    ['districtCode' => 'LAK', 'district' => 'Lakhisarai'],
                    ['districtCode' => 'MAD', 'district' => 'Madhepura'],
                    ['districtCode' => 'MADH', 'district' => 'Madhubani'],
                    ['districtCode' => 'MUN', 'district' => 'Munger'],
                    ['districtCode' => 'MUZ', 'district' => 'Muzaffarpur'],
                    ['districtCode' => 'NAL', 'district' => 'Nalanda'],
                    ['districtCode' => 'NAW', 'district' => 'Nawada'],
                    ['districtCode' => 'PAT', 'district' => 'Patna'],
                    ['districtCode' => 'PUR', 'district' => 'Purnia'],
                    ['districtCode' => 'ROH', 'district' => 'Rohtas'],
                    ['districtCode' => 'SAH', 'district' => 'Saharsa'],
                    ['districtCode' => 'SAM', 'district' => 'Samastipur'],
                    ['districtCode' => 'SAR', 'district' => 'Saran'],
                    ['districtCode' => 'SHE', 'district' => 'Sheikhpura'],
                    ['districtCode' => 'SHEO', 'district' => 'Sheohar'],
                    ['districtCode' => 'SIT', 'district' => 'Sitamarhi'],
                    ['districtCode' => 'SIW', 'district' => 'Siwan'],
                    ['districtCode' => 'SUP', 'district' => 'Supaul'],
                    ['districtCode' => 'VAI', 'district' => 'Vaishali'],
                    ['districtCode' => 'WES', 'district' => 'West Champaran'],
                ]
            ],
            [
                'stateCode' => 'CI',
                'state' => 'Chhattisgarh',
                'districts' => [
                    ['districtCode' => 'BAL', 'district' => 'Balod'],
                    ['districtCode' => 'BAL-B', 'district' => 'Baloda Bazar'],
                    ['districtCode' => 'BAL-R', 'district' => 'Balrampur'],
                    ['districtCode' => 'BAS', 'district' => 'Bastar'],
                    ['districtCode' => 'BEM', 'district' => 'Bemetara'],
                    ['districtCode' => 'BIJ', 'district' => 'Bijapur'],
                    ['districtCode' => 'BIL', 'district' => 'Bilaspur'],
                    ['districtCode' => 'DAN', 'district' => 'Dantewada (Dakshin Bastar)'],
                    ['districtCode' => 'DHA', 'district' => 'Dhamtari'],
                    ['districtCode' => 'DUR', 'district' => 'Durg'],
                    ['districtCode' => 'GAR', 'district' => 'Gariaband'],
                    ['districtCode' => 'GAU', 'district' => 'Gaurela-Pendra-Marwahi'],
                    ['districtCode' => 'JAN', 'district' => 'Janjgir-Champa'],
                    ['districtCode' => 'JAS', 'district' => 'Jashpur'],
                    ['districtCode' => 'KAB', 'district' => 'Kabirdham (Kawardha)'],
                    ['districtCode' => 'KAN', 'district' => 'Kanker (Uttar Bastar)'],
                    ['districtCode' => 'KON', 'district' => 'Kondagaon'],
                    ['districtCode' => 'KOR', 'district' => 'Korba'],
                    ['districtCode' => 'KOR-I', 'district' => 'Korea (Koriya)'],
                    ['districtCode' => 'MAH', 'district' => 'Mahasamund'],
                    ['districtCode' => 'MUN', 'district' => 'Mungeli'],
                    ['districtCode' => 'NAR', 'district' => 'Narayanpur'],
                    ['districtCode' => 'RAI', 'district' => 'Raigarh'],
                    ['districtCode' => 'RAI-I', 'district' => 'Raipur'],
                    ['districtCode' => 'RAJ', 'district' => 'Rajnandgaon'],
                    ['districtCode' => 'SUK', 'district' => 'Sukma'],
                    ['districtCode' => 'SUR', 'district' => 'Surajpur'],
                    ['districtCode' => 'SUR-I', 'district' => 'Surguja'],
                    ['districtCode' => 'MAN', 'district' => 'Manendragarh-Chirmiri-Bharatpur'],
                    ['districtCode' => 'KHA', 'district' => 'Khairagarh'],
                    ['districtCode' => 'MOH', 'district' => 'Mohla-Manpur'],
                    ['districtCode' => 'SAR', 'district' => 'Sarangarh-Bilaigarh'],
                    ['districtCode' => 'SAK', 'district' => 'Sakti'],
                ]
            ],
            [
                'stateCode' => 'GO',
                'state' => 'Goa',
                'districts' => [
                    ['districtCode' => 'NG', 'district' => 'North Goa'],
                    ['districtCode' => 'SG', 'district' => 'South Goa'],
                ]
            ],
            [
                'stateCode' => 'GJ',
                'state' => 'Gujarat',
                'districts' => [
                    ['districtCode' => 'AHE', 'district' => 'Ahmedabad'],
                    ['districtCode' => 'AMR', 'district' => 'Amreli'],
                    ['districtCode' => 'ANA', 'district' => 'Anand'],
                    ['districtCode' => 'ARA', 'district' => 'Aravalli'],
                    ['districtCode' => 'BAN', 'district' => 'Banaskantha'],
                    ['districtCode' => 'BHA', 'district' => 'Bharuch'],
                    ['districtCode' => 'BHV', 'district' => 'Bhavnagar'],
                    ['districtCode' => 'BOT', 'district' => 'Botad'],
                    ['districtCode' => 'CHH', 'district' => 'Chhota Udaipur'],
                    ['districtCode' => 'DAH', 'district' => 'Dahod'],
                    ['districtCode' => 'DAN', 'district' => 'Dang'],
                    ['districtCode' => 'DEB', 'district' => 'Devbhumi Dwarka'],
                    ['districtCode' => 'GAN', 'district' => 'Gandhinagar'],
                    ['districtCode' => 'GIR', 'district' => 'Gir Somnath'],
                    ['districtCode' => 'JAM', 'district' => 'Jamnagar'],
                    ['districtCode' => 'JUN', 'district' => 'Junagadh'],
                    ['districtCode' => 'KHE', 'district' => 'Kheda'],
                    ['districtCode' => 'KUT', 'district' => 'Kutch'],
                    ['districtCode' => 'MAH', 'district' => 'Mahisagar'],
                    ['districtCode' => 'MEH', 'district' => 'Mehsana'],
                    ['districtCode' => 'MOR', 'district' => 'Morbi'],
                    ['districtCode' => 'NAR', 'district' => 'Narmada'],
                    ['districtCode' => 'NAV', 'district' => 'Navsari'],
                    ['districtCode' => 'PAN', 'district' => 'Panchmahal'],
                    ['districtCode' => 'PAT', 'district' => 'Patan'],
                    ['districtCode' => 'POR', 'district' => 'Porbandar'],
                    ['districtCode' => 'RAJ', 'district' => 'Rajkot'],
                    ['districtCode' => 'SAB', 'district' => 'Sabarkantha'],
                    ['districtCode' => 'SUR', 'district' => 'Surat'],
                    ['districtCode' => 'SUR-I', 'district' => 'Surendranagar'],
                    ['districtCode' => 'TAP', 'district' => 'Tapi'],
                    ['districtCode' => 'VAD', 'district' => 'Vadodara'],
                    ['districtCode' => 'VAL', 'district' => 'Valsad'],
                ]
            ],
            [
                'stateCode' => 'HR',
                'state' => 'Haryana',
                'districts' => [
                    ['districtCode' => 'AMB', 'district' => 'Ambala'],
                    ['districtCode' => 'BHI', 'district' => 'Bhiwani'],
                    ['districtCode' => 'CHA', 'district' => 'Charkhi Dadri'],
                    ['districtCode' => 'FAR', 'district' => 'Faridabad'],
                    ['districtCode' => 'FAT', 'district' => 'Fatehabad'],
                    ['districtCode' => 'GUR', 'district' => 'Gurugram'],
                    ['districtCode' => 'HIS', 'district' => 'Hisar'],
                    ['districtCode' => 'JHA', 'district' => 'Jhajjar'],
                    ['districtCode' => 'JIN', 'district' => 'Jind'],
                    ['districtCode' => 'KAI', 'district' => 'Kaithal'],
                    ['districtCode' => 'KAR', 'district' => 'Karnal'],
                    ['districtCode' => 'KUR', 'district' => 'Kurukshetra'],
                    ['districtCode' => 'MAH', 'district' => 'Mahendragarh'],
                    ['districtCode' => 'NUH', 'district' => 'Nuh'],
                    ['districtCode' => 'PAL', 'district' => 'Palwal'],
                    ['districtCode' => 'PAN', 'district' => 'Panchkula'],
                    ['districtCode' => 'PAN-I', 'district' => 'Panipat'],
                    ['districtCode' => 'REW', 'district' => 'Rewari'],
                    ['districtCode' => 'ROH', 'district' => 'Rohtak'],
                    ['districtCode' => 'SIR', 'district' => 'Sirsa'],
                    ['districtCode' => 'SON', 'district' => 'Sonipat'],
                    ['districtCode' => 'YAM', 'district' => 'Yamunanagar'],
                ]
            ],
            [
                'stateCode' => 'HP',
                'state' => 'Himachal Pradesh',
                'districts' => [
                    ['districtCode' => 'BI', 'district' => 'Bilaspur'],
                    ['districtCode' => 'CH', 'district' => 'Chamba'],
                    ['districtCode' => 'HA', 'district' => 'Hamirpur'],
                    ['districtCode' => 'KA', 'district' => 'Kangra'],
                    ['districtCode' => 'KI', 'district' => 'Kinnaur'],
                    ['districtCode' => 'KU', 'district' => 'Kullu'],
                    ['districtCode' => 'LA', 'district' => 'Lahaul and Spiti'],
                    ['districtCode' => 'MA', 'district' => 'Mandi'],
                    ['districtCode' => 'SH', 'district' => 'Shimla'],
                    ['districtCode' => 'SI', 'district' => 'Sirmaur'],
                    ['districtCode' => 'SO', 'district' => 'Solan'],
                    ['districtCode' => 'UN', 'district' => 'Una'],
                ]
            ],
            [
                'stateCode' => 'JH',
                'state' => 'Jharkhand',
                'districts' => [
                    ['districtCode' => 'BOK', 'district' => 'Bokaro'],
                    ['districtCode' => 'CHA', 'district' => 'Chatra'],
                    ['districtCode' => 'DEO', 'district' => 'Deoghar'],
                    ['districtCode' => 'DHA', 'district' => 'Dhanbad'],
                    ['districtCode' => 'DUM', 'district' => 'Dumka'],
                    ['districtCode' => 'EAS', 'district' => 'East Singhbhum'],
                    ['districtCode' => 'GAR', 'district' => 'Garhwa'],
                    ['districtCode' => 'GOD', 'district' => 'Godda'],
                    ['districtCode' => 'HAZ', 'district' => 'Hazaribag'],
                    ['districtCode' => 'JAM', 'district' => 'Jamtara'],
                    ['districtCode' => 'KHU', 'district' => 'Khunti'],
                    ['districtCode' => 'KOD', 'district' => 'Koderma'],
                    ['districtCode' => 'LATE', 'district' => 'Latehar'],
                    ['districtCode' => 'LOH', 'district' => 'Lohardaga'],
                    ['districtCode' => 'PAK', 'district' => 'Pakur'],
                    ['districtCode' => 'PAL', 'district' => 'Palamu'],
                    ['districtCode' => 'RAM', 'district' => 'Ramgarh'],
                    ['districtCode' => 'RAN', 'district' => 'Ranchi'],
                    ['districtCode' => 'SAH', 'district' => 'Sahibganj'],
                    ['districtCode' => 'SER', 'district' => 'Seraikela-Kharsawan'],
                    ['districtCode' => 'SIM', 'district' => 'Simdega'],
                    ['districtCode' => 'WES', 'district' => 'West Singhbhum'],
                ]
            ],
            [
                'stateCode' => 'KA',
                'state' => 'Karnataka',
                'districts' => [
                    ['districtCode' => 'BAL', 'district' => 'Ballari'],
                    ['districtCode' => 'CHA', 'district' => 'Chamarajanagara'],
                    ['districtCode' => 'CHI', 'district' => 'Chikkaballapura'],
                    ['districtCode' => 'CHIT', 'district' => 'Chitradurga'],
                    ['districtCode' => 'DAK', 'district' => 'Dakshina Kannada'],
                    ['districtCode' => 'DAV', 'district' => 'Davanagere'],
                    ['districtCode' => 'HASS', 'district' => 'Hassan'],
                    ['districtCode' => 'KAL', 'district' => 'Kalaburagi'],
                    ['districtCode' => 'KOD', 'district' => 'Kodagu'],
                    ['districtCode' => 'KOP', 'district' => 'Koppala'],
                    ['districtCode' => 'MYS', 'district' => 'Mysuru'],
                    ['districtCode' => 'RAP', 'district' => 'Ramanagara'],
                    ['districtCode' => 'SHA', 'district' => 'Shivamogga'],
                    ['districtCode' => 'TUM', 'district' => 'Tumakuru'],
                    ['districtCode' => 'UDU', 'district' => 'Udupi'],
                ]
            ],
            [
                'stateCode' => 'KL',
                'state' => 'Kerala',
                'districts' => [
                    ['districtCode' => 'AL', 'district' => 'Alappuzha'],
                    ['districtCode' => 'ERI', 'district' => 'Ernakulam'],
                    ['districtCode' => 'ID', 'district' => 'Idukki'],
                    ['districtCode' => 'KAN', 'district' => 'Kannur'],
                    ['districtCode' => 'KAS', 'district' => 'Kasaragod'],
                    ['districtCode' => 'KO', 'district' => 'Kozhikode'],
                    ['districtCode' => 'MAL', 'district' => 'Malappuram'],
                    ['districtCode' => 'PAL', 'district' => 'Palakkad'],
                    ['districtCode' => 'PATH', 'district' => 'Pathanamthitta'],
                    ['districtCode' => 'THIR', 'district' => 'Thiruvananthapuram'],
                ]
            ],
            [
                'stateCode' => 'MP',
                'state' => 'Madhya Pradesh',
                'districts' => [
                    ['districtCode' => 'AG', 'district' => 'Agar Malwa'],
                    ['districtCode' => 'BAL', 'district' => 'Balaghat'],
                    ['districtCode' => 'BH', 'district' => 'Bhind'],
                    ['districtCode' => 'BHO', 'district' => 'Bhopal'],
                    ['districtCode' => 'BUR', 'district' => 'Burhanpur'],
                    ['districtCode' => 'CHH', 'district' => 'Chhatarpur'],
                    ['districtCode' => 'DAN', 'district' => 'Datia'],
                    ['districtCode' => 'DHA', 'district' => 'Dhar'],
                    ['districtCode' => 'DHE', 'district' => 'Dewas'],
                    ['districtCode' => 'GON', 'district' => 'Gondia'],
                    ['districtCode' => 'HIN', 'district' => 'Harda'],
                    ['districtCode' => 'IND', 'district' => 'Indore'],
                    ['districtCode' => 'JAB', 'district' => 'Jabalpur'],
                    ['districtCode' => 'JHA', 'district' => 'Jhabua'],
                    ['districtCode' => 'KHA', 'district' => 'Khandwa (East Nimar)'],
                    ['districtCode' => 'KHI', 'district' => 'Khargone (West Nimar)'],
                    ['districtCode' => 'MAL', 'district' => 'Mandla'],
                    ['districtCode' => 'MAND', 'district' => 'Mandsaur'],
                    ['districtCode' => 'R', 'district' => 'Raisen'],
                    ['districtCode' => 'RAJ', 'district' => 'Rajgarh'],
                    ['districtCode' => 'REW', 'district' => 'Rewa'],
                    ['districtCode' => 'SAG', 'district' => 'Sagar'],
                    ['districtCode' => 'SAT', 'district' => 'Satna'],
                    ['districtCode' => 'SEH', 'district' => 'Sehore'],
                    ['districtCode' => 'SEON', 'district' => 'Seoni'],
                    ['districtCode' => 'SHA', 'district' => 'Shahdol'],
                    ['districtCode' => 'SHJ', 'district' => 'Shajapur'],
                    ['districtCode' => 'SHE', 'district' => 'Sheopur'],
                    ['districtCode' => 'SHI', 'district' => 'Shivpuri'],
                    ['districtCode' => 'SID', 'district' => 'Sidhi'],
                    ['districtCode' => 'SIN', 'district' => 'Singrauli'],
                    ['districtCode' => 'TI', 'district' => 'Tikamgarh'],
                    ['districtCode' => 'UJ', 'district' => 'Ujjain'],
                    ['districtCode' => 'UMA', 'district' => 'Umaria'],
                    ['districtCode' => 'VID', 'district' => 'Vidisha'],
                ]
            ],
            [
                'stateCode' => 'MH',
                'state' => 'Maharashtra',
                'districts' => [
                    ['districtCode' => 'AHM', 'district' => 'Ahmednagar'],
                    ['districtCode' => 'AKO', 'district' => 'Akola'],
                    ['districtCode' => 'BE', 'district' => 'Beed'],
                    ['districtCode' => 'BUL', 'district' => 'Buldhana'],
                    ['districtCode' => 'CH', 'district' => 'Chandrapur'],
                    ['districtCode' => 'DHU', 'district' => 'Dhule'],
                    ['districtCode' => 'GAD', 'district' => 'Gadchiroli'],
                    ['districtCode' => 'JAL', 'district' => 'Jalgaon'],
                    ['districtCode' => 'JAL', 'district' => 'Jalna'],
                    ['districtCode' => 'KOL', 'district' => 'Kolhapur'],
                    ['districtCode' => 'LAT', 'district' => 'Latur'],
                    ['districtCode' => 'NAN', 'district' => 'Nanded'],
                    ['districtCode' => 'NAN', 'district' => 'Nandurbar'],
                    ['districtCode' => 'OSM', 'district' => 'Osmanabad'],
                    ['districtCode' => 'PAL', 'district' => 'Palghar'],
                    ['districtCode' => 'PUN', 'district' => 'Pune'],
                    ['districtCode' => 'PAR', 'district' => 'Parbhani'],
                    ['districtCode' => 'RAI', 'district' => 'Raigad'],
                    ['districtCode' => 'RAI', 'district' => 'Ratnagiri'],
                    ['districtCode' => 'SAT', 'district' => 'Satara'],
                    ['districtCode' => 'SIND', 'district' => 'Sindhudurg'],
                    ['districtCode' => 'SOL', 'district' => 'Solapur'],
                    ['districtCode' => 'THA', 'district' => 'Thane'],
                    ['districtCode' => 'WAD', 'district' => 'Wardha'],
                    ['districtCode' => 'WASH', 'district' => 'Washim'],
                    ['districtCode' => 'YAV', 'district' => 'Yavatmal'],
                ]
            ],
            [
                'stateCode' => 'MN',
                'state' => 'Manipur',
                'districts' => [
                    ['districtCode' => 'BIS', 'district' => 'Bishnupur'],
                    ['districtCode' => 'CHA', 'district' => 'Chandel'],
                    ['districtCode' => 'IMP_E', 'district' => 'Imphal East'],
                    ['districtCode' => 'IMP_W', 'district' => 'Imphal West'],
                    ['districtCode' => 'JIR', 'district' => 'Jiribam'],
                    ['districtCode' => 'KAK', 'district' => 'Kakching'],
                    ['districtCode' => 'KAM', 'district' => 'Kamjong'],
                    ['districtCode' => 'KANG', 'district' => 'Kangpokpi'],
                    ['districtCode' => 'NON', 'district' => 'Noney'],
                    ['districtCode' => 'PHER', 'district' => 'Pherzawl'],
                    ['districtCode' => 'TAM', 'district' => 'Tamenglong'],
                    ['districtCode' => 'TEN', 'district' => 'Tengnoupal'],
                    ['districtCode' => 'THO', 'district' => 'Thoubal'],
                    ['districtCode' => 'UKH', 'district' => 'Ukhrul'],
                ]
            ],
            [
                'stateCode' => 'ME',
                'state' => 'Meghalaya',
                'districts' => [
                    ['districtCode' => 'EAS_GAR', 'district' => 'East Garo Hills'],
                    ['districtCode' => 'EAS_KHA', 'district' => 'East Khasi Hills'],
                    ['districtCode' => 'EAS_JAI', 'district' => 'East Jaintia Hills'],
                    ['districtCode' => 'EAS_WES', 'district' => 'Eastern West Khasi Hills'],
                    ['districtCode' => 'WES_GAR', 'district' => 'West Garo Hills'],
                    ['districtCode' => 'WES_JAI', 'district' => 'West Jaintia Hills'],
                    ['districtCode' => 'WES_KHA', 'district' => 'West Khasi Hills'],
                ]
            ],
            [
                'stateCode' => 'MI',
                'state' => 'Mizoram',
                'districts' => [
                    ['districtCode' => 'AIZ', 'district' => 'Aizawl'],
                    ['districtCode' => 'CHAM', 'district' => 'Champhai'],
                    ['districtCode' => 'HNATH', 'district' => 'Hnahthial'],
                    ['districtCode' => 'KHI', 'district' => 'Kolasib'],
                    ['districtCode' => 'LUNG', 'district' => 'Lunglei'],
                    ['districtCode' => 'MAMI', 'district' => 'Mamit'],
                    ['districtCode' => 'SER', 'district' => 'Serchhip'],
                ]
            ],
            [
                'stateCode' => 'NA',
                'state' => 'Nagaland',
                'districts' => [
                    ['districtCode' => 'DIM', 'district' => 'Dimapur'],
                    ['districtCode' => 'KOH', 'district' => 'Kohima'],
                    ['districtCode' => 'LONG', 'district' => 'Longleng'],
                    ['districtCode' => 'MOK', 'district' => 'Mokokchung'],
                    ['districtCode' => 'MON', 'district' => 'Mon'],
                    ['districtCode' => 'PER', 'district' => 'Peren'],
                    ['districtCode' => 'PHE', 'district' => 'Phek'],
                    ['districtCode' => 'TUEN', 'district' => 'Tuensang'],
                    ['districtCode' => 'WOK', 'district' => 'Wokha'],
                    ['districtCode' => 'ZUN', 'district' => 'Zunheboto'],
                    ['districtCode' => 'CHU', 'district' => 'Chümoukedima'],
                    ['districtCode' => 'SEN', 'district' => 'Senapati'],
                    ['districtCode' => 'TSE', 'district' => 'Tseminyü'],
                    ['districtCode' => 'THO', 'district' => 'Thoubal'],
                    ['districtCode' => 'SAI', 'district' => 'Saiha'],
                    ['districtCode' => 'NOK', 'district' => 'Nokla'],
                    ['districtCode' => 'NIU', 'district' => 'Niuland'],
                    ['districtCode' => 'SOUT', 'district' => 'South West Garo Hills'],
                    ['districtCode' => 'SO', 'district' => 'South West Khasi Hills'],
                    ['districtCode' => 'TAM', 'district' => 'Tamenglong']
                ]
            ],
            [
                'stateCode' => 'OD',
                'state' => 'Odisha',
                'districts' => [
                    ['districtCode' => 'ANG', 'district' => 'Angul'],
                    ['districtCode' => 'BA', 'district' => 'Boudh (Bauddh)'],
                    ['districtCode' => 'BH', 'district' => 'Bhadrak'],
                    ['districtCode' => 'BA', 'district' => 'Balasore (Baleswar, Baleshwar)'],
                    ['districtCode' => 'BU', 'district' => 'Bargarh (Baragarh, Baragad)'],
                    ['districtCode' => 'GA', 'district' => 'Ganjam'],
                    ['districtCode' => 'GA', 'district' => 'Gajapati'],
                    ['districtCode' => 'DE', 'district' => 'Debagarh (Deogarh, Debagad)'],
                    ['districtCode' => 'DH', 'district' => 'Dhenkanal'],
                    ['districtCode' => 'CU', 'district' => 'Cuttack (Katak)'],
                    ['districtCode' => 'JA', 'district' => 'Jajpur'],
                    ['districtCode' => 'JA', 'district' => 'Jagatsinghpur'],
                    ['districtCode' => 'KH', 'district' => 'Khordha'],
                    ['districtCode' => 'KE', 'district' => 'Kendujhar'],
                    ['districtCode' => 'KA', 'district' => 'Kalahandi'],
                    ['districtCode' => 'KA', 'district' => 'Kandhamal'],
                    ['districtCode' => 'KO', 'district' => 'Koraput'],
                    ['districtCode' => 'KE', 'district' => 'Kendrapara (Kendrapada)'],
                    ['districtCode' => 'MA', 'district' => 'Malkangiri'],
                    ['districtCode' => 'MU', 'district' => 'Mayurbhanj'],
                    ['districtCode' => 'NA', 'district' => 'Nabarangpur'],
                    ['districtCode' => 'NU', 'district' => 'Nuapada'],
                    ['districtCode' => 'NA', 'district' => 'Nayagarh (Nayagad)'],
                    ['districtCode' => 'PU', 'district' => 'Puri'],
                    ['districtCode' => 'SA', 'district' => 'Sambalpur'],
                    ['districtCode' => 'SU', 'district' => 'Subarnapur (Sonepur)'],
                    ['districtCode' => 'SU', 'district' => 'Sundargarh'],
                ]
            ],
            [
                'stateCode' => 'PB',
                'state' => 'Punjab',
                'districts' => [
                    ['districtCode' => 'AM', 'district' => 'Amritsar'],
                    ['districtCode' => 'BA', 'district' => 'Barnala'],
                    ['districtCode' => 'FI', 'district' => 'Firozpur'],
                    ['districtCode' => 'FA', 'district' => 'Faridkot'],
                    ['districtCode' => 'GA', 'district' => 'Gurdaspur'],
                    ['districtCode' => 'HA', 'district' => 'Hoshiarpur'],
                    ['districtCode' => 'JA', 'district' => 'Jalandhar'],
                    ['districtCode' => 'KA', 'district' => 'Kapurthala'],
                    ['districtCode' => 'MA', 'district' => 'Mansa'],
                    ['districtCode' => 'MO', 'district' => 'Moga'],
                    ['districtCode' => 'SA', 'district' => 'Sahibzada Ajit Singh Nagar'],
                    ['districtCode' => 'PAT', 'district' => 'Patiala'],
                    ['districtCode' => 'SH', 'district' => 'Shahid Bhagat Singh Nagar'],
                    ['districtCode' => 'TAR', 'district' => 'Tarn Taran'],
                ]
            ],
            [
                'stateCode' => 'RJ',
                'state' => 'Rajasthan',
                'districts' => [
                    ['districtCode' => 'AJM', 'district' => 'Ajmer'],
                    ['districtCode' => 'AL', 'district' => 'Alwar'],
                    ['districtCode' => 'BA', 'district' => 'Barmer'],
                    ['districtCode' => 'BA', 'district' => 'Banswara'],
                    ['districtCode' => 'BI', 'district' => 'Bikaner'],
                    ['districtCode' => 'CH', 'district' => 'Churu'],
                    ['districtCode' => 'DA', 'district' => 'Dausa'],
                    ['districtCode' => 'DH', 'district' => 'Dholpur'],
                    ['districtCode' => 'DU', 'district' => 'Dungarpur'],
                    ['districtCode' => 'JA', 'district' => 'Jaipur'],
                    ['districtCode' => 'JA', 'district' => 'Jaisalmer'],
                    ['districtCode' => 'JH', 'district' => 'Jhunjhunu'],
                    ['districtCode' => 'JH', 'district' => 'Jhalawar'],
                    ['districtCode' => 'KA', 'district' => 'Karauli'],
                    ['districtCode' => 'NA', 'district' => 'Nagaur'],
                    ['districtCode' => 'RA', 'district' => 'Rajsamand'],
                    ['districtCode' => 'SA', 'district' => 'Sawai Madhopur'],
                    ['districtCode' => 'SI', 'district' => 'Sikar'],
                    ['districtCode' => 'SI', 'district' => 'Sirohi'],
                    ['districtCode' => 'TO', 'district' => 'Tonk'],
                    ['districtCode' => 'UD', 'district' => 'Udaipur'],
                ]
            ],
            [
                'stateCode' => 'SI',
                'state' => 'Sikkim',
                'districts' => [
                    ['districtCode' => 'CH', 'district' => 'Chamling'],
                    ['districtCode' => 'EA', 'district' => 'East Sikkim'],
                    ['districtCode' => 'NO', 'district' => 'North Sikkim'],
                    ['districtCode' => 'SO', 'district' => 'South Sikkim'],
                    ['districtCode' => 'WE', 'district' => 'West Sikkim']
                ]
            ],
            [
                'stateCode' => 'tN',
                'state' => 'Tamil Nadu',
                'districts' => [
                    ['districtCode' => 'AR', 'district' => 'Ariyalur'],
                    ['districtCode' => 'CO', 'district' => 'Coimbatore'],
                    ['districtCode' => 'DH', 'district' => 'Dharmapuri'],
                    ['districtCode' => 'ER', 'district' => 'Erode'],
                    ['districtCode' => 'KA', 'district' => 'Kanyakumari'],
                    ['districtCode' => 'KA', 'district' => 'Karur'],
                    ['districtCode' => 'KI', 'district' => 'Krishnagiri'],
                    ['districtCode' => 'MA', 'district' => 'Madurai'],
                    ['districtCode' => 'MI', 'district' => 'Mayiladuthurai'],
                    ['districtCode' => 'NA', 'district' => 'Nagapattinam'],
                    ['districtCode' => 'NI', 'district' => 'Nilgiris'],
                    ['districtCode' => 'NA', 'district' => 'Namakkal'],
                    ['districtCode' => 'PE', 'district' => 'Perambalur'],
                    ['districtCode' => 'PU', 'district' => 'Pudukkottai'],
                    ['districtCode' => 'RA', 'district' => 'Ramanathapuram'],
                    ['districtCode' => 'RA', 'district' => 'Ranipet'],
                    ['districtCode' => 'SA', 'district' => 'Salem'],
                    ['districtCode' => 'SI', 'district' => 'Sivaganga'],
                    ['districtCode' => 'TE', 'district' => 'Tenkasi'],
                    ['districtCode' => 'TI', 'district' => 'Tiruppur'],
                    ['districtCode' => 'TI', 'district' => 'Tiruchirappalli'],
                    ['districtCode' => 'TH', 'district' => 'Theni'],
                    ['districtCode' => 'TI', 'district' => 'Tirunelveli'],
                    ['districtCode' => 'TH', 'district' => 'Thanjavur'],
                    ['districtCode' => 'TH', 'district' => 'Thoothukudi'],
                    ['districtCode' => 'TI', 'district' => 'Tirupattur'],
                    ['districtCode' => 'TI', 'district' => 'Tiruvallur'],
                    ['districtCode' => 'TI', 'district' => 'Tiruvarur'],
                    ['districtCode' => 'TI', 'district' => 'Tiruvannamalai'],
                    ['districtCode' => 'VE', 'district' => 'Vellore'],
                    ['districtCode' => 'VI', 'district' => 'Viluppuram'],
                    ['districtCode' => 'VI', 'district' => 'Virudhunagar'],
                ]
            ],
            [
                'stateCode' => 'TS',
                'state' => 'Telangana',
                'districts' => [
                    ['districtCode' => 'AD', 'district' => 'Adilabad'],
                    ['districtCode' => 'BH', 'district' => 'Bhadradri Kothagudem'],
                    ['districtCode' => 'HA', 'district' => 'Hanamkonda'],
                    ['districtCode' => 'JA', 'district' => 'Jagtial'],
                    ['districtCode' => 'KA', 'district' => 'Karimnagar'],
                    ['districtCode' => 'KO', 'district' => 'Kumuram Bheem Asifabad'],
                    ['districtCode' => 'MA', 'district' => 'Mahabubabad'],
                    ['districtCode' => 'ME', 'district' => 'Medak'],
                    ['districtCode' => 'NA', 'district' => 'Nalgonda'],
                    ['districtCode' => 'NA', 'district' => 'Narayanpet'],
                    ['districtCode' => 'PA', 'district' => 'Peddapalli'],
                    ['districtCode' => 'RA', 'district' => 'Ranga Reddy'],
                    ['districtCode' => 'SA', 'district' => 'Sangareddy'],
                    ['districtCode' => 'SI', 'district' => 'Siddipet'],
                    ['districtCode' => 'SU', 'district' => 'Suryapet'],
                    ['districtCode' => 'VI', 'district' => 'Vikarabad'],
                    ['districtCode' => 'WA', 'district' => 'Wanaparthy'],
                    ['districtCode' => 'WA', 'district' => 'Warangal'],
                    ['districtCode' => 'YA', 'district' => 'Yadadri Bhuvanagiri'],
                ]
            ],
            [
                'stateCode' => 'TR',
                'state' => 'Tripura',
                'districts' => [
                    ['districtCode' => 'DH', 'district' => 'Dhalai'],
                    ['districtCode' => 'GO', 'district' => 'Gomati'],
                    ['districtCode' => 'KH', 'district' => 'Khowai'],
                    ['districtCode' => 'NO', 'district' => 'North Tripura'],
                    ['districtCode' => 'SE', 'district' => 'Sepahijala'],
                    ['districtCode' => 'SO', 'district' => 'South Tripura'],
                    ['districtCode' => 'WE', 'district' => 'West Tripura'],
                ]
            ],
            [
                'stateCode' => 'UT',
                'state' => 'Uttarakhand',
                'districts' => [
                    ['districtCode' => 'AL', 'district' => 'Almora'],
                    ['districtCode' => 'CH', 'district' => 'Champawat'],
                    ['districtCode' => 'DE', 'district' => 'Dehradun'],
                    ['districtCode' => 'DH', 'district' => 'Dharampur'],
                    ['districtCode' => 'HAR', 'district' => 'Haridwar'],
                    ['districtCode' => 'NA', 'district' => 'Nainital'],
                    ['districtCode' => 'PA', 'district' => 'Pauri Garhwal'],
                    ['districtCode' => 'PU', 'district' => 'Pithoragarh'],
                    ['districtCode' => 'RI', 'district' => 'Rudraprayag'],
                    ['districtCode' => 'TE', 'district' => 'Tehri Garhwal'],
                    ['districtCode' => 'UT', 'district' => 'Uttarkashi'],
                ]
            ],
            [
                'stateCode' => 'WB',
                'state' => 'West Bengal',
                'districts' => [
                    ['districtCode' => 'AL', 'district' => 'Alipurduar'],
                    ['districtCode' => 'BA', 'district' => 'Bankura'],
                    ['districtCode' => 'BI', 'district' => 'Birbhum'],
                    ['districtCode' => 'CO', 'district' => 'Cooch Behar'],
                    ['districtCode' => 'DA', 'district' => 'Dakshin Dinajpur'],
                    ['districtCode' => 'HO', 'district' => 'Hooghly'],
                    ['districtCode' => 'JA', 'district' => 'Jalpaiguri'],
                    ['districtCode' => 'JU', 'district' => 'Jhargram'],
                    ['districtCode' => 'KA', 'district' => 'Kalimpong'],
                    ['districtCode' => 'KO', 'district' => 'Kolkata'],
                    ['districtCode' => 'MA', 'district' => 'Maldah'],
                    ['districtCode' => 'MU', 'district' => 'Murshidabad'],
                    ['districtCode' => 'NA', 'district' => 'Nadia'],
                    ['districtCode' => 'PA', 'district' => 'Paschim Bardhaman'],
                    ['districtCode' => 'PM', 'district' => 'Paschim Medinipur'],
                    ['districtCode' => 'PU', 'district' => 'Purba Bardhaman'],
                    ['districtCode' => 'PU', 'district' => 'Purba Medinipur'],
                    ['districtCode' => 'PU', 'district' => 'Purulia'],
                    ['districtCode' => 'SA', 'district' => 'South 24 Parganas'],
                    ['districtCode' => 'UP', 'district' => 'Uttar Dinajpur']
                ]
            ],
            [
                'stateCode' => 'AN',
                'state' => 'Andaman and Nicobar',
                'districts' => [
                    ['districtCode' => 'NI', 'district' => 'Nicobar'],
                    ['districtCode' => 'NO', 'district' => 'North and Middle Andaman'],
                    ['districtCode' => 'SO', 'district' => 'South Andaman'],
                ]
            ],
            [
                'stateCode' => 'DL',
                'state' => 'Delhi',
                'districts' => [
                    ['districtCode' => 'CE', 'district' => 'Central Delhi'],
                    ['districtCode' => 'NE', 'district' => 'North East Delhi'],
                    ['districtCode' => 'NW', 'district' => 'North West Delhi'],
                    ['districtCode' => 'NO', 'district' => 'North Delhi'],
                    ['districtCode' => 'SA', 'district' => 'South Delhi'],
                    ['districtCode' => 'SE', 'district' => 'South East Delhi'],
                    ['districtCode' => 'SW', 'district' => 'South West Delhi'],
                    ['districtCode' => 'WE', 'district' => 'West Delhi'],
                    ['districtCode' => 'SH', 'district' => 'Shahdara'],
                ]
            ],
            [
                'stateCode' => 'PY',
                'state' => 'Puducherry',
                'districts' => [
                    ['districtCode' => 'KA', 'district' => 'Karaikal'],
                    ['districtCode' => 'MA', 'district' => 'Mahe'],
                    ['districtCode' => 'YA', 'district' => 'Yanam'],
                ]
            ],
            [
                'stateCode' => 'LA',
                'state' => 'Ladakh',
                'districts' => [
                    ['districtCode' => 'LE', 'district' => 'Leh'],
                    ['districtCode' => 'KA', 'district' => 'Kargil'],
                ]
            ],
            [
                'stateCode' => 'JK',
                'state' => 'Jammu and Kashmir',
                'districts' => [
                    ['districtCode' => 'AN', 'district' => 'Anantnag'],
                    ['districtCode' => 'BA', 'district' => 'Baramulla'],
                    ['districtCode' => 'BA', 'district' => 'Bandipore'],
                    ['districtCode' => 'BU', 'district' => 'Budgam'],
                    ['districtCode' => 'DA', 'district' => 'Doda'],
                    ['districtCode' => 'GA', 'district' => 'Ganderbal'],
                    ['districtCode' => 'JA', 'district' => 'Jammu'],
                    ['districtCode' => 'KA', 'district' => 'Kathua'],
                    ['districtCode' => 'KI', 'district' => 'Kishtwar'],
                    ['districtCode' => 'KU', 'district' => 'Kulgam'],
                    ['districtCode' => 'KU', 'district' => 'Kupwara'],
                    ['districtCode' => 'PO', 'district' => 'Poonch'],
                    ['districtCode' => 'PU', 'district' => 'Pulwama'],
                    ['districtCode' => 'RA', 'district' => 'Rajouri'],
                    ['districtCode' => 'RA', 'district' => 'Ramban'],
                    ['districtCode' => 'RE', 'district' => 'Reasi'],
                    ['districtCode' => 'SA', 'district' => 'Samba'],
                    ['districtCode' => 'SH', 'district' => 'Shopian'],
                    ['districtCode' => 'SR', 'district' => 'Srinagar'],
                    ['districtCode' => 'UD', 'district' => 'Udhampur']
                ]
            ],
            [
                'stateCode' => 'UP',
                'state' => 'Uttar Pradesh',
                'districts' => [
                    ['districtCode' => 'AG', 'district' => 'Agra'],
                    ['districtCode' => 'AL', 'district' => 'Aligarh'],
                    ['districtCode' => 'AN', 'district' => 'Ambedkar Nagar'],
                    ['districtCode' => 'AM', 'district' => 'Amethi'],
                    ['districtCode' => 'AR', 'district' => 'Amroha'],
                    ['districtCode' => 'AU', 'district' => 'Auraiya'],
                    ['districtCode' => 'AY', 'district' => 'Ayodhya'],
                    ['districtCode' => 'AZ', 'district' => 'Azamgarh'],
                    ['districtCode' => 'BG', 'district' => 'Baghpat'],
                    ['districtCode' => 'BH', 'district' => 'Bahraich'],
                    ['districtCode' => 'BA', 'district' => 'Ballia'],
                    ['districtCode' => 'BP', 'district' => 'Balrampur'],
                    ['districtCode' => 'BD', 'district' => 'Banda'],
                    ['districtCode' => 'BK', 'district' => 'Barabanki'],
                    ['districtCode' => 'BR', 'district' => 'Bareilly'],
                    ['districtCode' => 'BS', 'district' => 'Basti'],
                    ['districtCode' => 'BV', 'district' => 'Bhadohi'],
                    ['districtCode' => 'BN', 'district' => 'Bijnor'],
                    ['districtCode' => 'BU', 'district' => 'Budaun'],
                    ['districtCode' => 'BSR', 'district' => 'Bulandshahr'],
                    ['districtCode' => 'CL', 'district' => 'Chandauli'],
                    ['districtCode' => 'CK', 'district' => 'Chitrakoot'],
                    ['districtCode' => 'DE', 'district' => 'Deoria'],
                    ['districtCode' => 'ET', 'district' => 'Etah'],
                    ['districtCode' => 'EW', 'district' => 'Etawah'],
                    ['districtCode' => 'FR', 'district' => 'Farrukhabad'],
                    ['districtCode' => 'FP', 'district' => 'Fatehpur'],
                    ['districtCode' => 'FZ', 'district' => 'Firozabad'],
                    ['districtCode' => 'GBN', 'district' => 'Gautam Buddha Nagar'],
                    ['districtCode' => 'GZ', 'district' => 'Ghaziabad'],
                    ['districtCode' => 'GH', 'district' => 'Ghazipur'],
                    ['districtCode' => 'GD', 'district' => 'Gonda'],
                    ['districtCode' => 'GP', 'district' => 'Gorakhpur'],
                    ['districtCode' => 'HP', 'district' => 'Hamirpur'],
                    ['districtCode' => 'HR', 'district' => 'Hapur'],
                    ['districtCode' => 'HD', 'district' => 'Hardoi'],
                    ['districtCode' => 'HT', 'district' => 'Hathras'],
                    ['districtCode' => 'JL', 'district' => 'Jalaun'],
                    ['districtCode' => 'JN', 'district' => 'Jaunpur'],
                    ['districtCode' => 'JH', 'district' => 'Jhansi'],
                    ['districtCode' => 'KJ', 'district' => 'Kannauj'],
                    ['districtCode' => 'KD', 'district' => 'Kanpur Dehat'],
                    ['districtCode' => 'KN', 'district' => 'Kanpur Nagar'],
                    ['districtCode' => 'KG', 'district' => 'Kasganj'],
                    ['districtCode' => 'KB', 'district' => 'Kaushambi'],
                    ['districtCode' => 'KU', 'district' => 'Kushinagar'],
                    ['districtCode' => 'LK', 'district' => 'Lakhimpur Kheri'],
                    ['districtCode' => 'LP', 'district' => 'Lalitpur'],
                    ['districtCode' => 'LK', 'district' => 'Lucknow'],
                    ['districtCode' => 'MJ', 'district' => 'Maharajganj'],
                    ['districtCode' => 'MH', 'district' => 'Mahoba'],
                    ['districtCode' => 'MP', 'district' => 'Mainpuri'],
                    ['districtCode' => 'MT', 'district' => 'Mathura'],
                    ['districtCode' => 'MW', 'district' => 'Mau'],
                    ['districtCode' => 'MR', 'district' => 'Meerut'],
                    ['districtCode' => 'MZ', 'district' => 'Mirzapur'],
                    ['districtCode' => 'MD', 'district' => 'Moradabad'],
                    ['districtCode' => 'MN', 'district' => 'Muzaffarnagar'],
                    ['districtCode' => 'PB', 'district' => 'Pilibhit'],
                    ['districtCode' => 'PG', 'district' => 'Pratapgarh'],
                    ['districtCode' => 'PY', 'district' => 'Prayagraj'],
                    ['districtCode' => 'RB', 'district' => 'Raebareli'],
                    ['districtCode' => 'RM', 'district' => 'Rampur'],
                    ['districtCode' => 'SR', 'district' => 'Saharanpur'],
                    ['districtCode' => 'SM', 'district' => 'Sambhal'],
                    ['districtCode' => 'SK', 'district' => 'Sant Kabir Nagar'],
                    ['districtCode' => 'SJ', 'district' => 'Shahjahanpur'],
                    ['districtCode' => 'SL', 'district' => 'Shamli'],
                    ['districtCode' => 'SV', 'district' => 'Shravasti'],
                    ['districtCode' => 'SN', 'district' => 'Siddharthnagar'],
                    ['districtCode' => 'SP', 'district' => 'Sitapur'],
                    ['districtCode' => 'SB', 'district' => 'Sonbhadra'],
                    ['districtCode' => 'ST', 'district' => 'Sultanpur'],
                    ['districtCode' => 'UN', 'district' => 'Unnao'],
                    ['districtCode' => 'VN', 'district' => 'Varanasi'],
                ]
            ],
        ];
        foreach ($states as $state) {
            $state_id = DB::table('states')->insertGetId([
                'name' => $state['state'],
                'state_code' => $state['stateCode'],
            ]);

            $districts = array_map(function ($district) use ($state_id) {
                return array_merge($district, ['state_id' => $state_id]);
            }, $state['districts']);
            foreach ($districts as $district) {
                Dist::create([
                    'name' => $district['district'],
                    'dist_code' => $district['districtCode'],
                    'state_id' => $district['state_id'],
                ]);
            }
        }
    }
}
